### ISSUE TITLE
std::call_once needs pthread

### ISSUE THREAD

**Issue by Yangxiu123321** [openppl-public/ppl.common#1]
`const CpuInfo* GetCpuInfo(int) {
    std::call_once(__st_cpuinfo_once_flag, &detect_cpuinfo_once);
    return &__st_cpuinfo;
}`

调用
`const struct ppl::common::CpuInfo* cpuinfo = ppl::common::GetCpuInfo(0);`

报错
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
已放弃 (核心已转储)

需要自己加-lpthread

**Comment by openppl-public** [comment]
> const

Fixed.
